import { Market } from "./types/market";

export const MARKETS: Market[] = [
  // ASIA PACIFIC
  // India
  {
    id: "in-en",
    region: "asia-pacific",
    country: "India",
    countryCode: "IN",
    language: "English",
    locale: "en-IN",
    currency: "INR",
    currencySymbol: "₹",
    timezone: "Asia/Kolkata",
    numberFormat: "en-IN",
    dateFormat: "en-IN",
    defaultLanguage: true,
    isDefault: true,
  },
  {
    id: "in-hi",
    region: "asia-pacific",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    locale: "hi-IN",
    currency: "INR",
    currencySymbol: "₹",
    timezone: "Asia/Kolkata",
    numberFormat: "hi-IN",
    dateFormat: "hi-IN",
    defaultLanguage: false,
    isDefault: false,
  },
  // Singapore
  {
    id: "sg-en",
    region: "asia-pacific",
    country: "Singapore",
    countryCode: "SG",
    language: "English",
    locale: "en-SG",
    currency: "SGD",
    currencySymbol: "S$",
    timezone: "Asia/Singapore",
    numberFormat: "en-SG",
    dateFormat: "en-SG",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "sg-zh",
    region: "asia-pacific",
    country: "Singapore",
    countryCode: "SG",
    language: "Chinese (Simplified)",
    locale: "zh-SG",
    currency: "SGD",
    currencySymbol: "S$",
    timezone: "Asia/Singapore",
    numberFormat: "zh-SG",
    dateFormat: "zh-SG",
    defaultLanguage: false,
    isDefault: false,
  },
  // Japan
  {
    id: "jp-ja",
    region: "asia-pacific",
    country: "Japan",
    countryCode: "JP",
    language: "Japanese",
    locale: "ja-JP",
    currency: "JPY",
    currencySymbol: "¥",
    timezone: "Asia/Tokyo",
    numberFormat: "ja-JP",
    dateFormat: "ja-JP",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "jp-en",
    region: "asia-pacific",
    country: "Japan",
    countryCode: "JP",
    language: "English",
    locale: "en-JP",
    currency: "JPY",
    currencySymbol: "¥",
    timezone: "Asia/Tokyo",
    numberFormat: "en-JP",
    dateFormat: "en-JP",
    defaultLanguage: false,
    isDefault: false,
  },
  // China
  {
    id: "cn-zh",
    region: "asia-pacific",
    country: "China",
    countryCode: "CN",
    language: "Chinese (Simplified)",
    locale: "zh-CN",
    currency: "CNY",
    currencySymbol: "¥",
    timezone: "Asia/Shanghai",
    numberFormat: "zh-CN",
    dateFormat: "zh-CN",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "cn-en",
    region: "asia-pacific",
    country: "China",
    countryCode: "CN",
    language: "English",
    locale: "en-CN",
    currency: "CNY",
    currencySymbol: "¥",
    timezone: "Asia/Shanghai",
    numberFormat: "en-CN",
    dateFormat: "en-CN",
    defaultLanguage: false,
    isDefault: false,
  },
  // South Korea
  {
    id: "kr-ko",
    region: "asia-pacific",
    country: "South Korea",
    countryCode: "KR",
    language: "Korean",
    locale: "ko-KR",
    currency: "KRW",
    currencySymbol: "₩",
    timezone: "Asia/Seoul",
    numberFormat: "ko-KR",
    dateFormat: "ko-KR",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "kr-en",
    region: "asia-pacific",
    country: "South Korea",
    countryCode: "KR",
    language: "English",
    locale: "en-KR",
    currency: "KRW",
    currencySymbol: "₩",
    timezone: "Asia/Seoul",
    numberFormat: "en-KR",
    dateFormat: "en-KR",
    defaultLanguage: false,
    isDefault: false,
  },
  // Australia
  {
    id: "au-en",
    region: "asia-pacific",
    country: "Australia",
    countryCode: "AU",
    language: "English",
    locale: "en-AU",
    currency: "AUD",
    currencySymbol: "A$",
    timezone: "Australia/Sydney",
    numberFormat: "en-AU",
    dateFormat: "en-AU",
    defaultLanguage: true,
    isDefault: false,
  },
  // MIDDLE EAST
  // United Arab Emirates
  {
    id: "ae-ar",
    region: "middle-east",
    country: "United Arab Emirates",
    countryCode: "AE",
    language: "Arabic",
    locale: "ar-AE",
    currency: "AED",
    currencySymbol: "د.إ",
    timezone: "Asia/Dubai",
    numberFormat: "ar-AE",
    dateFormat: "ar-AE",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "ae-en",
    region: "middle-east",
    country: "United Arab Emirates",
    countryCode: "AE",
    language: "English",
    locale: "en-AE",
    currency: "AED",
    currencySymbol: "د.إ",
    timezone: "Asia/Dubai",
    numberFormat: "en-AE",
    dateFormat: "en-AE",
    defaultLanguage: false,
    isDefault: false,
  },
  // Saudi Arabia
  {
    id: "sa-ar",
    region: "middle-east",
    country: "Saudi Arabia",
    countryCode: "SA",
    language: "Arabic",
    locale: "ar-SA",
    currency: "SAR",
    currencySymbol: "ر.س",
    timezone: "Asia/Riyadh",
    numberFormat: "ar-SA",
    dateFormat: "ar-SA",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "sa-en",
    region: "middle-east",
    country: "Saudi Arabia",
    countryCode: "SA",
    language: "English",
    locale: "en-SA",
    currency: "SAR",
    currencySymbol: "ر.س",
    timezone: "Asia/Riyadh",
    numberFormat: "en-SA",
    dateFormat: "en-SA",
    defaultLanguage: false,
    isDefault: false,
  },
  // Qatar
  {
    id: "qa-ar",
    region: "middle-east",
    country: "Qatar",
    countryCode: "QA",
    language: "Arabic",
    locale: "ar-QA",
    currency: "QAR",
    currencySymbol: "ر.ق",
    timezone: "Asia/Qatar",
    numberFormat: "ar-QA",
    dateFormat: "ar-QA",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "qa-en",
    region: "middle-east",
    country: "Qatar",
    countryCode: "QA",
    language: "English",
    locale: "en-QA",
    currency: "QAR",
    currencySymbol: "ر.ق",
    timezone: "Asia/Qatar",
    numberFormat: "en-QA",
    dateFormat: "en-QA",
    defaultLanguage: false,
    isDefault: false,
  },
  // Bahrain
  {
    id: "bh-ar",
    region: "middle-east",
    country: "Bahrain",
    countryCode: "BH",
    language: "Arabic",
    locale: "ar-BH",
    currency: "BHD",
    currencySymbol: "د.ب",
    timezone: "Asia/Bahrain",
    numberFormat: "ar-BH",
    dateFormat: "ar-BH",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "bh-en",
    region: "middle-east",
    country: "Bahrain",
    countryCode: "BH",
    language: "English",
    locale: "en-BH",
    currency: "BHD",
    currencySymbol: "د.ب",
    timezone: "Asia/Bahrain",
    numberFormat: "en-BH",
    dateFormat: "en-BH",
    defaultLanguage: false,
    isDefault: false,
  },
  // Kuwait
  {
    id: "kw-ar",
    region: "middle-east",
    country: "Kuwait",
    countryCode: "KW",
    language: "Arabic",
    locale: "ar-KW",
    currency: "KWD",
    currencySymbol: "د.ك",
    timezone: "Asia/Kuwait",
    numberFormat: "ar-KW",
    dateFormat: "ar-KW",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "kw-en",
    region: "middle-east",
    country: "Kuwait",
    countryCode: "KW",
    language: "English",
    locale: "en-KW",
    currency: "KWD",
    currencySymbol: "د.ك",
    timezone: "Asia/Kuwait",
    numberFormat: "en-KW",
    dateFormat: "en-KW",
    defaultLanguage: false,
    isDefault: false,
  },
  // Oman
  {
    id: "om-ar",
    region: "middle-east",
    country: "Oman",
    countryCode: "OM",
    language: "Arabic",
    locale: "ar-OM",
    currency: "OMR",
    currencySymbol: "ر.ع.",
    timezone: "Asia/Muscat",
    numberFormat: "ar-OM",
    dateFormat: "ar-OM",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "om-en",
    region: "middle-east",
    country: "Oman",
    countryCode: "OM",
    language: "English",
    locale: "en-OM",
    currency: "OMR",
    currencySymbol: "ر.ع.",
    timezone: "Asia/Muscat",
    numberFormat: "en-OM",
    dateFormat: "en-OM",
    defaultLanguage: false,
    isDefault: false,
  },
  // EUROPE
  // Spain
  {
    id: "es-es",
    region: "europe",
    country: "Spain",
    countryCode: "ES",
    language: "Spanish",
    locale: "es-ES",
    currency: "EUR",
    currencySymbol: "€",
    timezone: "Europe/Madrid",
    numberFormat: "es-ES",
    dateFormat: "es-ES",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "es-en",
    region: "europe",
    country: "Spain",
    countryCode: "ES",
    language: "English",
    locale: "en-ES",
    currency: "EUR",
    currencySymbol: "€",
    timezone: "Europe/Madrid",
    numberFormat: "en-ES",
    dateFormat: "en-ES",
    defaultLanguage: false,
    isDefault: false,
  },
  // Italy
  {
    id: "it-it",
    region: "europe",
    country: "Italy",
    countryCode: "IT",
    language: "Italian",
    locale: "it-IT",
    currency: "EUR",
    currencySymbol: "€",
    timezone: "Europe/Rome",
    numberFormat: "it-IT",
    dateFormat: "it-IT",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "it-en",
    region: "europe",
    country: "Italy",
    countryCode: "IT",
    language: "English",
    locale: "en-IT",
    currency: "EUR",
    currencySymbol: "€",
    timezone: "Europe/Rome",
    numberFormat: "en-IT",
    dateFormat: "en-IT",
    defaultLanguage: false,
    isDefault: false,
  },
  // France
  {
    id: "fr-fr",
    region: "europe",
    country: "France",
    countryCode: "FR",
    language: "French",
    locale: "fr-FR",
    currency: "EUR",
    currencySymbol: "€",
    timezone: "Europe/Paris",
    numberFormat: "fr-FR",
    dateFormat: "fr-FR",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "fr-en",
    region: "europe",
    country: "France",
    countryCode: "FR",
    language: "English",
    locale: "en-FR",
    currency: "EUR",
    currencySymbol: "€",
    timezone: "Europe/Paris",
    numberFormat: "en-FR",
    dateFormat: "en-FR",
    defaultLanguage: false,
    isDefault: false,
  },
  // Germany
  {
    id: "de-de",
    region: "europe",
    country: "Germany",
    countryCode: "DE",
    language: "German",
    locale: "de-DE",
    currency: "EUR",
    currencySymbol: "€",
    timezone: "Europe/Berlin",
    numberFormat: "de-DE",
    dateFormat: "de-DE",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "de-en",
    region: "europe",
    country: "Germany",
    countryCode: "DE",
    language: "English",
    locale: "en-DE",
    currency: "EUR",
    currencySymbol: "€",
    timezone: "Europe/Berlin",
    numberFormat: "en-DE",
    dateFormat: "en-DE",
    defaultLanguage: false,
    isDefault: false,
  },
  // United Kingdom
  {
    id: "gb-en",
    region: "europe",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    locale: "en-GB",
    currency: "GBP",
    currencySymbol: "£",
    timezone: "Europe/London",
    numberFormat: "en-GB",
    dateFormat: "en-GB",
    defaultLanguage: true,
    isDefault: false,
  },
  // Switzerland
  {
    id: "ch-en",
    region: "europe",
    country: "Switzerland",
    countryCode: "CH",
    language: "English",
    locale: "en-CH",
    currency: "CHF",
    currencySymbol: "CHF",
    timezone: "Europe/Zurich",
    numberFormat: "en-CH",
    dateFormat: "en-CH",
    defaultLanguage: true,
    isDefault: false,
  },
  // NORTH AMERICA
  // United States
  {
    id: "us-en",
    region: "north-america",
    country: "United States",
    countryCode: "US",
    language: "English",
    locale: "en-US",
    currency: "USD",
    currencySymbol: "$",
    timezone: "America/New_York",
    numberFormat: "en-US",
    dateFormat: "en-US",
    defaultLanguage: true,
    isDefault: false,
  },
  // Canada
  {
    id: "ca-en",
    region: "north-america",
    country: "Canada",
    countryCode: "CA",
    language: "English",
    locale: "en-CA",
    currency: "CAD",
    currencySymbol: "CA$",
    timezone: "America/Toronto",
    numberFormat: "en-CA",
    dateFormat: "en-CA",
    defaultLanguage: true,
    isDefault: false,
  },
  {
    id: "ca-fr",
    region: "north-america",
    country: "Canada",
    countryCode: "CA",
    language: "French",
    locale: "fr-CA",
    currency: "CAD",
    currencySymbol: "CA$",
    timezone: "America/Toronto",
    numberFormat: "fr-CA",
    dateFormat: "fr-CA",
    defaultLanguage: false,
    isDefault: false,
  },
  // SOUTH AMERICA
  // Brazil
  {
    id: "br-en",
    region: "south-america",
    country: "Brazil",
    countryCode: "BR",
    language: "English",
    locale: "en-BR",
    currency: "BRL",
    currencySymbol: "R$",
    timezone: "America/Sao_Paulo",
    numberFormat: "en-BR",
    dateFormat: "en-BR",
    defaultLanguage: true,
    isDefault: false,
  },
  // AFRICA
  // South Africa
  {
    id: "za-en",
    region: "africa",
    country: "South Africa",
    countryCode: "ZA",
    language: "English",
    locale: "en-ZA",
    currency: "ZAR",
    currencySymbol: "R",
    timezone: "Africa/Johannesburg",
    numberFormat: "en-ZA",
    dateFormat: "en-ZA",
    defaultLanguage: true,
    isDefault: false,
  },
];
