import { IAnalyticsRepository } from "@/lib/analytics/repositories/IAnalyticsRepository";
import { AnalyticsEvent } from "@/lib/analytics/core/types";
import { IDatabaseDriver } from "../../drivers/IDatabaseDriver";

export class AnalyticsRepository implements IAnalyticsRepository {
  private collection = "analytics_events";

  constructor(private driver: IDatabaseDriver) {}

  async store(event: AnalyticsEvent): Promise<void> {
    // We use event.id generated by client or server as the document ID
    await this.driver.write(this.collection, event.id, event);
  }
}
