export enum PersistenceEvent {
  DATABASE_CONNECTED = "DATABASE_CONNECTED",
  DATABASE_DISCONNECTED = "DATABASE_DISCONNECTED",
  MIGRATION_STARTED = "MIGRATION_STARTED",
  MIGRATION_COMPLETED = "MIGRATION_COMPLETED",
  MIGRATION_FAILED = "MIGRATION_FAILED",
  TRANSACTION_COMMITTED = "TRANSACTION_COMMITTED",
  TRANSACTION_ROLLED_BACK = "TRANSACTION_ROLLED_BACK",
}
